
channels:
- conda-forge
dependencies:
- python=3.11.14
- pip<=25.2
- pip:
  - mlflow==2.19.0
  - cloudpickle==1.6.0
  - numpy==2.1.3
  - pandas==2.3.3
  - psutil==7.1.3
  - pyarrow==18.1.0
  - scikit-learn==1.7.2
  - scipy==1.16.3
name: mlflow-env